### PR TITLE
Gfs/add win7 support

### PR DESCRIPTION
**Pull request by gfs**
Adds Windows + 32bit Windows support.
Makefile fixes.
Change to have Gui place NOTICE on build.

### CODE REVIEW

**Comment by gfs** [comment]
Testing this now.  Ran into missing on KBs on the image fresh from MSDN.

https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#net-core-supported-windows-versions

**Comment by scovetta** [comment]
Are the NOTICE files identical? Could we just have one of those, and grab it for each build?

**Comment by gfs** [comment]
We could set the cloud build up to place them. That is what I did for the GUI versions - I think you're right I'll update the pipeline + solutions.

**Comment by gfs** [comment]
Fixed using project files.

**Comment by gfs** [comment]
Tested on a Windows 7 VM. Adding a FAQ entry for the KBs you need.

**Comment by gfs** [comment]
Fixed pipeline builds fine now.

**Pull request merged**
