### PR TITLE
#650 bump bootstrap version

### PR DESCRIPTION
**Pull request by WingZer0o**
I bumped the bootstrap JS and CSS to v5.2.3 and fixed a small UI issue on the home page.

I targeted the wrong branch in my last PR which is why I closed it. This is based off release/v2.3.

Let me know if any other UI issues have arisen.

### CODE REVIEW

**Comment by gfs** [comment]
Nice, looks like pretty simple changes. I need to track down why the pipeline didn't run correctly here and manually pull this down to check that everything still seems to work, so likely will be next week when this can merge.

**Comment by WingZer0o** [comment]
Sounds good.

**Review by gfs — APPROVED** [review]
LGTM. Manually run the GUI, don't notice anything else out of place. Thanks for the contribution!

**Review by scovetta — APPROVED** [review]

**Pull request merged**
