### PR TITLE
Adds a first-run notice informing user of telemetry.

### PR DESCRIPTION
**Pull request by gfs**
Open to suggestions on wording. What I've used is ```This application collects usage data to help us improve Attack Surface Analyzer. For our privacy policy visit: {1}. To disable telemetry run '{0}'.```
image

### CODE REVIEW

**Comment by scovetta** [comment]
Suggest a newline to separate the sentences, and adding the CLI name (args[0]?), e.g.:

```
This application collects usage data to help us improve Attack Surface Analyzer. 
For our privacy policy visit: {1}.
To disable telemetry run 'AttackSurfaceAnalyzer.exe {0}'.
```

**Comment by gfs** [comment]
Updated per Mike's suggestions. 
image

**Comment by gfs** [comment]
Screen Shot 2019-04-23 at 10 44 21 AM

Here's the latest iteration. @scovetta  does this look good to you?

**Comment by gfs** [comment]
@guydalf can you take a look as well? I updated PRIVACY.md already.

**Pull request merged**
