### PR TITLE
Add Component Detection task explicitly.

### PR DESCRIPTION
**Pull request by scovetta**

### CODE REVIEW

**Comment by gfs** [comment]
Looks like it's failing due to a new scan task that doesn't like the Asa sample docker files. I think it's fine to just remove the dicker files. I'm not aware of any usage.

**Comment by scovetta** [comment]
> Looks like it's failing due to a new scan task that doesn't like the Asa sample docker files. I think it's fine to just remove the docker files. I'm not aware of any usage.

It's actually due to new restrictions on pulling from Docker Hub directly (due to throttling), so I changed to pull from mcr instead.

**Review by gfs — APPROVED** [review]

**Comment by scovetta** [comment]
The Docker fix worked, but the Component Detection task didn't find anything -- I'll try to move the task somewhere else.

**Comment by scovetta** [comment]
@gfs Looks like it worked, packages are now being picked up.

**Comment by gfs** [comment]
Looks good then. Fine to merge when you like.

**Pull request merged**
